import React from 'react';

export const metadata = {
  title: 'Privacy Policy | Liquidation Port',
  description: 'Privacy Policy for Liquidation Port',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <h1 className="text-4xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
      <div className="text-gray-700 space-y-6">
        <p>
          As used in this policy, the terms “using” and “processing” information include using cookies on a computer, subjecting the information to statistical or other analysis and using or handling information in any way, including, but not limited to collecting, storing, evaluating, modifying, deleting, using, combining, disclosing and transferring information within our organization or among our affiliates within the United States or Internationally.
        </p>

        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">1. Personally Identifiable Information</h2>
        <p>
          When you register with us through the Site or Applications to become a Member of DirectLiquidation.com, we may ask you for personally identifiable information. This refers to information about you that can be used to contact or identify you (“Personal Information”). Personal Information includes, but is not limited to, your name, username, phone number, credit card and other billing information, email address, shipping address, and your friend’s email addresses (which we will only use in order to invite them to use the service). We may also collect information you supply to us regarding your personal preferences and interests. You can choose not to provide us with any or all of the information we specify or request, but then you may not be able to register with us or to take advantage of some or all of our features.
        </p>
        <p>
          You can register to join DirectLiquidation.com via the Site or Applications or by logging into your account with certain third party social networking sites (“SNS”) (including Facebook and Twitter) via our Site. If you decide to create your account by logging into an SNS via the Site, we may extract the Personal Information you have provided to the SNS (such as your “real” name, email address and other information you make publicly available via the SNS) from the account you have with such SNS and use that information to create your Account; the information we extract may depend on the privacy settings you have with the SNS. We use your Personal Information mainly to provide the Service and administer your inquiries. We will create an account for you to use the Site and Applications based upon the Personal Information you provide and you will become a Member of the DirectLiquidation.com marketplace. We also collect other information that you provide as part of registration, administration and personalization of your profile page on DirectLiquidation.com (e.g., without limitation, age and individual preferences) (“Non-Identifying Information”). We use your Personal Information (in some cases, in conjunction with your Non-Identifying Information) mainly to provide the Service, complete your transactions, and administer your inquiries. Certain Non-Identifying Information would be considered a part of your Personal Information if it were combined with other identifiers (for example, combining your zip code with your street address) in a way that enables you to be identified. But the same pieces of information are considered Non-Identifying Information when they are taken alone or combined only with other non-identifying information (for example, your viewing preferences). We may combine your Personal Information with Non-Identifying Information and aggregate it with information collected from other Users of DirectLiquidation.com (defined below) to attempt to provide you with a better experience, to improve the quality and value of the Service and to analyze and understand how our Site, Applications and Service are used. We may also use the combined information without aggregating it to serve you specifically, for instance, to deliver a product to you according to your preferences or restrictions. We also use your Personal Information to contact you with DirectLiquidation.com newsletters, marketing or promotional materials and other information that may be of interest to you. If you decide at any time that you no longer wish to receive such communications from us, please follow the unsubscribe instructions provided in any of the communications or update your “preferences” information in your DirectLiquidation.com profile. (See “Changing or Deleting Information,” below.)
        </p>

        <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Log Data</h3>
        <p>
          When you visit the Site or Applications, whether as a Member or a non-registered user just browsing (“DirectLiquidation.com User”), our servers automatically record information that your browser sends whenever you visit a website (“Log Data”). This Log Data may include information such as your Internet Protocol address, the browser type or the webpage you were visiting before you came to our Site and or Applications, pages of our Site and Applications that you visit, the time spent on those pages, information you search for on our Site and Applications, access times and dates, and other statistics. We may use this information to monitor and analyze usage of the Site, Applications and/or to Service the Site and Applications’ technical administration, to increase our Site and Applications’ functionality and user-friendliness, and to better tailor our Site and Applications to our visitor’s needs. For example, some of this information is collected so that when you visit the Site and Applications again, it may recognize you and serve advertisements and other information appropriate to your interests. We also use this information to verify that visitors to the Site and Applications meet the criteria required to process their requests. We do not treat Log Data as Personal Information or use it in association with other Personal Information, though we may aggregate, analyze and evaluate such information for the same purposes as stated above regarding other Non-Identifying Information.
        </p>

        <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Device Information</h3>
        <p>
          In addition to Log Data, we may also collect information about the device you’re using to access DirectLiquidation.com, including what type of device it is, what operating system you’re using, device settings, unique device identifiers, and crash data. Whether we collect some or all of this information depends on what type of device you’re using and its settings. To learn more about what information your device makes available to us, please also check the policies of your device manufacturer or software provider.
        </p>

        <h3 className="text-xl font-semibold text-gray-900 mt-6 mb-3">Use of Your Personal Data when using the Chatbot</h3>
        <p>
          You are not required to provide any personal information when using the Chatbot. However, if you do provide such personal information, we may use such information for the following purposes:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>To provide and maintain our Service, including to monitor the usage of our Service and to be able to respond to your questions.</li>
        </ul>

        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">2. Information Sharing</h2>
        <ul className="list-disc pl-6 space-y-4">
          <li><strong>Members:</strong> In addition to your username, any Non-Identifying Information that you choose to provide (e.g., without limitation, age and individual preferences) will be publicly available on your Profile and to other DirectLiquidation.com Users. You may also choose to share certain Personal Information with other DirectLiquidation.com Users by providing such information on your Profile. We do not share your Personal Information with other DirectLiquidation.com Users except as provided in this Privacy Policy.</li>
          <li><strong>Aggregate Information and Non-Identifying Information:</strong> We may share aggregated information that does not include Personal Information and we may otherwise disclose Non-Identifying Information and Log Data with third parties for industry analysis, demographic profiling and other purposes. Any aggregated information shared in these contexts will not contain your Personal Information.</li>
          <li><strong>Service Providers:</strong> We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Site and Application-related services (e.g., without limitation, maintenance services, database management, web analytics and improvement of the Site and Application features) or to assist us in analyzing how our Site, Applications and Service are used. These third parties have access to your Personal Information only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose. We may also provide Personal Information to our business partners or other trusted entities for the purpose of providing you with information on goods or services we believe will be of interest to you. You can, at any time, opt out of receiving such communications.</li>
          <li><strong>Compliance with Laws and Law Enforcement:</strong> Direct Liquidation, LLP. cooperates with government and law enforcement officials and private parties to enforce and comply with the law. We will disclose any information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate to respond to claims and legal process (including but not limited to subpoenas), to protect the property and rights of Direct Liquidation, LLP. or a third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, illegal, unethical or legally actionable activity.</li>
          <li><strong>Business Transfers:</strong> Direct Liquidation, LLP. may sell, transfer or otherwise share some or all of its assets, including your Personal Information, in connection with a merger, acquisition, reorganization or sale of assets or in the event of bankruptcy.</li>
        </ul>

        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">3. Cookies</h2>
        <p>Like many websites, we use “cookies” to collect information. A cookie is a small data file that we transfer to your computer’s hard disk for record-keeping purposes. We use cookies for two purposes. First, we utilize persistent cookies to save your registration ID and login password for future logins to the Site and Applications. Second, we utilize session ID cookies to enable certain features of the Site and Applications, to better understand how you interact with the Site and Applications and to monitor aggregate usage by DirectLiquidation.com Users and web traffic routing on the Site and Applications. Unlike persistent cookies, session cookies are deleted from your computer when you log off from the Site, Applications and Service and then close your browser. Third party advertisers on the Site and Applications may also place or read cookies on your browser. You can instruct your browser, by changing its options, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. If you do not accept cookies, however, you may not be able to use all portions of the Site or Applications or all functionality of the Service.</p>

        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">4. Changing or Deleting Your Information</h2>
        <p>All Members may review, update, correct or delete the Personal Information in their Account by contacting us or by editing such profile information via the Site and Applications. If you completely delete all such information, then your Account may become deactivated. We will use commercially reasonable efforts to honor your request. We may retain an archived copy of your records as required by law or for legitimate business purposes.</p>

        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">5. Security</h2>
        <p>We may make any legally required disclosures of any breach of the security, confidentiality, or integrity of your unencrypted electronically stored “personal data” (as defined in applicable state statutes on security breach notification) to you via email or conspicuous posting on this Site or via the Applications in the most expedient time possible and without unreasonable delay, insofar as it is consistent with (i) the legitimate needs of law enforcement or (ii) any measures necessary to determine the scope of the breach and restore the reasonable integrity of the data system.</p>

        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">6. International Transfer</h2>
        <p>Your information may be transferred to and stored on computers located outside of your state, province, country or other governmental jurisdiction where the privacy laws may not be as protective as those in your jurisdiction. If you are located outside the United States and choose to provide information to us, Direct Liquidation, LLP. transfers Personal Information to the United States and processes it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>

        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">7. Links to Other Sites</h2>
        <p>Our Site and Applications may contain links to other websites. If you choose to visit an advertiser by “clicking on” a banner ad or other type of advertisement, or click on another third party link, you will be directed to that third party’s website. The fact that we link to a website or present a banner ad or other type of advertisement is not an endorsement, authorization or representation of our affiliation with that third party, nor is it an endorsement of their privacy or information security policies or practices. We do not exercise control over third party websites. These other websites may place their own cookies or other files on your computer, collect data or solicit personal information from you. Other sites follow different rules regarding the use or disclosure of the personal information you submit to them. We encourage you to read the privacy policies or statements of the other websites you visit.</p>

        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">8. Our Policy Toward Children</h2>
        <p>This Site and Applications are not directed to children under 13 years of age. We do not knowingly collect personally identifiable information from children under 13 years of age. If a parent or guardian becomes aware that his or her child has provided us with Personal Information without their consent, he or she should contact us at info@directliquidation.com. If we become aware that a child under 13 years of age has provided us with Personal Information, we will delete such information from our files.</p>

        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">9. Merchant Privacy Statement: How We Protect Your Credit Card Information</h2>
        <p>At DirectLiquidation.com, we are committed to protecting the privacy of each member’s financial information. To that end, we implement and maintain extensive physical, electronic, and procedural safeguards at all times in compliance with federal regulations. This is to protect your information while conducting business via our online platforms, wire services, standing orders and other DirectLiquidation.com channels. We ensure the highest level of security on our credit card transactions, and have many security features in place to minimize and/or block unauthorized activity. You may hear of security breaches that arise from hackers illegally accessing databases of merchants. DirectLiquidation.com is not at fault for those breaches, and takes steps to minimize the chance that a compromised card will be used fraudulently. As a safety precaution, you should always closely monitor activity on your accounts to ensure there is no unexplained or suspicious activity. If you are billed for a transaction that you did not perform, please be sure to notify us immediately.</p>

        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">10. How to contact us</h2>
        <p>If you have any questions about this Policy or any of the practices described herein, please email us at <a href="mailto:info@directliquidation.com" className="text-primary hover:underline">info@directliquidation.com</a>.</p>

        <p className="mt-8 font-semibold text-gray-900">Note: This Privacy Policy is in effect as of June 1, 2015</p>
      </div>
    </div>
  );
}
